-- AlterTable
ALTER TABLE `ModeloDocumento` MODIFY `tipo` ENUM('PROPOSTA', 'CONTRATO', 'BRIEFING', 'ESCOPO', 'ONBOARDING', 'CHECKLIST', 'ATA', 'RELATORIO', 'PAUTA_REUNIAO', 'PAUTA_POSTAGEM', 'RECIBO', 'DIAGNOSTICO', 'PLANO_ACAO') NOT NULL;
